info: "vae-8*128-orth_mpi_large_scale"
model:
  base_learning_rate: 4.5e-5
  num_epochs: 1000 
  batch_size: 8
  num_workers: 12
  distributed: True
  save_dir: "xxx"
  target: ldm.models.autoencoder.AutoencoderKL
  save_period: 1  
  log_period: 200
  params:
    monitor: "val/rec_loss"
    embed_dim: 8
    ddconfig:
      double_z: True
      z_channels: 8
      resolution: 512
      in_channels: 128
      out_ch: 128
      ch: 128
      ch_mult: [1,2,4]  # num_down = len(ch_mult)-1 
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0
  loss:
    params:
      disc_start: 50001
      kl_weight: 0.000001
      disc_weight: 0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    wrap: True
    train:
      target: ldm.data.imagenet.ImageNetSRTrain
      params:
        size: 256
        degradation: pil_nearest
    validation:
      target: ldm.data.imagenet.ImageNetSRValidation
      params:
        size: 256
        degradation: pil_nearest
